[package]
name = "ip_manager"
version = "0.1.0"
authors = ["pbzweihander <sd852456@naver.com>"]

[dependencies]
rocket = "0.3"
rocket_codegen = "0.3"
rocket_contrib = "0.3"
toml = "0.4"
serde_derive = "1.0"
serde = "1.0"
config = "0.7"
